### PR TITLE
[cmake] Find qpoases through cmake.

### PR DESCRIPTION
**Pull request by olivier-stasse**

### CODE REVIEW

**Comment by nim65s** [comment]
Have you checked robotpkg/path/hpp-constraints/patches/patch-aa ?

**Comment by nim65s** [comment]
As we have multiple packages that rely on qpOASES, I think that we should put this .cmake file in the JRL cmake submodule

**Comment by olivier-stasse** [comment]
We could but in general people tend to switch to quadprog which is faster.

**Comment by flforget** [comment]
I'm currently working on switching from qpOASES to quadprog. I will raise a PR as soon as it is ready

**Comment by olivier-stasse** [comment]
Thanks

**Pull request merged**
